### ISSUE TITLE
Custom events are not loaded on the front end

### ISSUE THREAD

**Issue by DannyWPWS** [WPWhiteSecurity/wsal-extension-template#19]
Just working on WC and when I visit a product as a logged in user, im getting the following error

````
[08-Oct-2020 15:33:58 UTC] PHP Fatal error:  Uncaught Exception: Event with code 9073 has not be registered. in /home/daniel/Local Sites/wsal-woocommerce/app/public/wp-content/plugins/wp-security-audit-log-premium/classes/AlertManager.php:372
Stack trace:
#0 /home/daniel/Local Sites/wsal-woocommerce/app/public/wp-content/plugins/wp-security-audit-log-premium/classes/AlertManager.php(368): WSAL_AlertManager->_CommitItem(9073, Array, NULL, false)
#1 /home/daniel/Local Sites/wsal-woocommerce/app/public/wp-content/plugins/wp-security-audit-log-premium/classes/AlertManager.php(293): WSAL_AlertManager->_CommitItem(9073, Array, NULL)
#2 /home/daniel/Local Sites/wsal-woocommerce/app/public/wp-content/plugins/wsal-woocommerce/wp-security-audit-log/custom-sensors/WSAL_Sensors_WooCommerce.php(1128): WSAL_AlertManager->Trigger(9073, Array)
#3 /home/daniel/Local Sites/wsal-woocommerce/app/public/wp-includes/class-wp-hook.php(287): WSAL_Sensors_WooCommerce->viewing_product('')
#4 /home/daniel/Local Sites/wsal-woocommerce/app/public/wp-includes/class-wp-hook.php(311): in /home/daniel/Local Sites/wsal-woocommerce/app/public/wp-content/plugins
````

To remedy I can run add_custom_sensors_and_events_dirs on init - will check with @martinkrcho if this is correct

````
add_action( 'wsal_before_sensor_load', array( $this, 'add_custom_sensors_and_events_dirs' ) );
````

**Comment by robert81** [comment]
@DannyWPWS can you please check this and advise?

**Comment by DannyWPWS** [comment]
Not a problem anymore, working really nicely 

![image](https://user-images.githubusercontent.com/59394454/111765190-00862880-889c-11eb-8229-a6b86f39fc7a.png)

Closing this up
